import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,readFileSync,statSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../core/store.mjs';
import {Backups} from '../core/backups.mjs';
import {snapshot,readImport,exportJSON,applyImport,mergePlan,validateData} from '../core/data-transfer.mjs';
function setup(t){const dir=mkdtempSync(join(tmpdir(),'chai-transfer-'));const stores=[];t.after(()=>{for(const s of stores)s.close();rmSync(dir,{recursive:true,force:true});});const create=name=>{const s=new Store(join(dir,name+'.sqlite'));stores.push(s);return s;};return {dir,create};}
function quote(store,name='Import example'){const template=store.rpc('templates.list').find(t=>t.code==='loan-refinance-title');return store.rpc('quotations.save',{template_id:template.id,input:{client_name:name,status:'draft',quotation_date:'2026-09-06',loan_amount:500000,ccm_search_amount:0,finance_legal_fee:false,finance_insurance:false}});}
test('JSON export and SQLite WAL import retain complete quote snapshots without changing source',async t=>{const {dir,create}=setup(t),source=create('source'),q=quote(source);const before=statSync(source.path).mtimeMs;const data=readImport(source.path);assert.equal(JSON.parse(data.quotations[0].body).calculation.summary.total_payable,q.calculation.summary.total_payable);assert.equal(statSync(source.path).mtimeMs,before);const json=join(dir,'data.json');exportJSON(source,json);assert.deepEqual(readImport(json).quotations,JSON.parse(JSON.stringify(data.quotations)));assert.throws(()=>exportJSON(source,json),/exist/i);});
test('merge adds new quotations, skips duplicate records, and preserves conflicts',t=>{const {create}=setup(t),source=create('source'),dest=create('dest'),q=quote(source);const data=snapshot(source);applyImport(dest,data,'restore');const edited=dest.rpc('quotations.get',{id:q.id});dest.rpc('quotations.save',{id:q.id,revision:edited.revision,input:{...edited.input,client_name:'Keep local edit'}});const second=quote(source,'Second quote');const imported=snapshot(source),plan=mergePlan(dest,imported);assert.equal(plan.quotations.length,1);assert.equal(plan.conflicts.length,1);const result=applyImport(dest,imported);assert.equal(result.quotations,1);assert.equal(result.skipped,4);assert.equal(dest.quote(q.id).input.client_name,'Keep local edit');assert.equal(dest.quote(second.id).input.client_name,'Second quote');assert.equal(applyImport(dest,imported).quotations,0);});
test('restore replaces contents only in the supplied destination and retains frozen template versions',t=>{const {create}=setup(t),source=create('source'),dest=create('restored');const q=quote(source);const data=snapshot(source);quote(dest,'Before restore');applyImport(dest,data,'restore');assert.deepEqual(snapshot(dest).quotations,data.quotations);assert.deepEqual(snapshot(dest).templates,data.templates);assert.equal(source.quote(q.id).number,q.number);});
test('invalid format, newer versions, duplicate records and broken snapshots fail before modification',t=>{const {create,dir}=setup(t),store=create('source');quote(store);const original=snapshot(store);for(const mutate of [d=>d.version=999,d=>d.quotations.push(d.quotations[0]),d=>d.templates[0].body='not json',d=>{const q=JSON.parse(d.quotations[0].body);q.calculation.summary.sst=-1;d.quotations[0].body=JSON.stringify(q);}]){const bad=structuredClone(original);mutate(bad);assert.throws(()=>applyImport(store,bad),/Invalid import/);assert.deepEqual(snapshot(store).quotations,original.quotations);}const file=join(dir,'bad.json');writeFileSync(file,'{"wrong":true}');assert.throws(()=>readImport(file),/Invalid import/);});
test('merge transaction rolls back all records on SQL failure',t=>{const {create}=setup(t),source=create('source'),dest=create('dest');quote(source);const original=snapshot(dest);dest.db.exec("CREATE TRIGGER fail_import BEFORE INSERT ON quotations BEGIN SELECT RAISE(ABORT,'test failure'); END;");assert.throws(()=>applyImport(dest,snapshot(source),'restore'),/test failure/);assert.deepEqual(snapshot(dest).templates,original.templates);assert.deepEqual(snapshot(dest).quotations,original.quotations);});
test('daily backups are scoped to each database and restoreable; manual backups are retained',async t=>{const {create,dir}=setup(t),a=create('a'),b=create('b');quote(a);const backupsA=new Backups(join(dir,'backups'),a.path),backupsB=new Backups(join(dir,'backups'),b.path);const first=await backupsA.daily(a);assert.ok(first);assert.equal(await backupsA.daily(a),null);assert.ok(await backupsB.daily(b));const manual=await backupsA.create(a);const safety=await backupsA.create(a,'before-import');assert.equal(readImport(first).quotations.length,1);assert.ok(existsSync(manual)&&existsSync(safety));assert.equal(backupsA.list().length,4);assert.throws(()=>backupsA.path('../bad.sqlite'),/not found/);});
test('incomplete backups never appear in backup history',async t=>{const {dir}=setup(t);const backups=new Backups(join(dir,'backups'));await assert.rejects(backups.create({backupTo:async file=>{writeFileSync(file,'partial');throw new Error('disk full');}}),/disk full/);assert.equal(backups.list().length,0);});
